#!/usr/bin/env node
// Generate maintained instruction copies from the four skill entrypoints.
// Runtime consumers use the checked-in JSON; installation does not run a builder.
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const check = process.argv.includes('--check');

// Normalize physical line endings before serialization: escaped CRs inside
// JSON/TOML strings survive Git's checkout conversion and cause permanent drift.
const normalizeEol = text => text.replace(/\r\n/g, '\n');

function skillBody(name) {
  const text = normalizeEol(fs.readFileSync(path.join(ROOT, 'skills', name, 'SKILL.md'), 'utf8'));
  if (!/^---\n[\s\S]*?\n---\n/.test(text)) {
    throw new Error('Missing skill frontmatter: ' + name);
  }
  return text.replace(/^---\n[\s\S]*?\n---\n/, '').trim();
}

function section(body, name) {
  const start = '<!-- h-mode:' + name + ':start -->';
  const end = '<!-- h-mode:' + name + ':end -->';
  const a = body.indexOf(start), b = body.indexOf(end);
  if (a < 0 || b <= a || body.indexOf(start, a + 1) !== -1 || body.indexOf(end, b + 1) !== -1) {
    throw new Error('Missing or ambiguous skill section: ' + name);
  }
  const result = body.slice(a + start.length, b).replace(/<!-- h-mode:[^>]*-->/g, '').trim();
  if (!result) throw new Error('Empty skill section: ' + name);
  return result;
}

const descriptions = {
  'h-mode': 'Concise, complete coding; activate H-Mode or turn it off.',
  'h-mode-audit': 'Read-only audit of code and prose with evidence, impact, and confidence.',
  'h-mode-review': 'Read-only complexity review with behavior-preserving recommendations.',
  'h-mode-help': 'H-Mode commands, activation, and platform differences.',
};
const bodies = Object.fromEntries(Object.keys(descriptions).map(name => [name, skillBody(name)]));
const core = section(bodies['h-mode'], 'core');
const reminder = section(bodies['h-mode'], 'reminder').replace(/\s+/g, ' ');
const warning = '<!-- Generated by scripts/build-rules.js from skills/h-mode/SKILL.md. -->\n';
const frontmatter = {
  '.cursor/rules/h-mode.mdc': '---\ndescription: H-Mode — concise, complete work and reuse-first code\nalwaysApply: true\n---\n\n',
  '.windsurf/rules/h-mode.md': '---\ntrigger: always_on\n---\n\n',
  '.clinerules/h-mode.md': '',
  '.kiro/steering/h-mode.md': '---\ninclusion: always\n---\n\n',
  '.github/copilot-instructions.md': '',
  'AGENTS.md': '',
  'GEMINI.md': '',
  'rules/h-mode-activate.md': '',
};
const outputs = Object.entries(frontmatter).map(([file, fm]) => [
  file, fm + warning + '# H-Mode\n\n' + core + '\n',
]);
outputs.push(['hooks/h-mode-instructions.json', JSON.stringify({
  reminder: 'H-MODE ACTIVE. ' + reminder,
  fallback: 'H-MODE ACTIVE\n\n' + core,
}, null, 2) + '\n']);

for (const [name, description] of Object.entries(descriptions)) {
  // Embed the actual skill so the command works without a separate skill loader.
  const body = bodies[name].replace(/<!-- h-mode:[^>]*-->\n?/g, '')
    .replace(/\]\(references\//g, '](skills/' + name + '/references/');
  const routing = name === 'h-mode'
    ? 'If the arguments are off, stop, or disable, deactivate H-Mode. Otherwise apply the following skill.\n\n'
    : 'Apply the following one-shot skill without activating persistent H-Mode.\n\n';
  outputs.push(['commands/' + name + '.toml',
    '# Generated by scripts/build-rules.js from skills/' + name + '/SKILL.md.\n' +
    'description = ' + JSON.stringify(description) + '\n' +
    'prompt = ' + JSON.stringify(routing + body + '\n\nUser arguments or request: {{args}}') + '\n',
  ]);
}

let drift = 0;
for (const [file, want] of outputs) {
  const absolute = path.join(ROOT, file);
  if (check) {
    let have = '';
    try { have = normalizeEol(fs.readFileSync(absolute, 'utf8')); } catch (_) {}
    if (have !== want) { console.error('OUT OF SYNC: ' + file); drift++; }
  } else {
    fs.mkdirSync(path.dirname(absolute), { recursive: true });
    fs.writeFileSync(absolute, want);
    console.log('wrote ' + file);
  }
}
if (drift) {
  console.error('Run node scripts/build-rules.js to synchronize instruction copies.');
  process.exitCode = 1;
} else if (check) {
  console.log('All instruction copies in sync (' + outputs.length + ' files).');
}
