#!/usr/bin/env node
// Extracts the June suite's real answers into site/src/data/samples.json so the
// website can show a live before/after built from committed transcripts rather
// than a hand-written mock-up.
//
// This is the whole point: the numbers and the prose are the same artefact the
// benchmarks are computed from. Nothing here is written for the website.
//
// Run:  node scripts/build-samples.js          (write)
//       node scripts/build-samples.js --check   (fail if stale; for CI)

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const RAW = path.join(ROOT, 'benchmarks', 'results', 'raw');
const OUT = path.join(ROOT, 'site', 'src', 'data', 'samples.json');

const ARMS = ['vanilla', 'caveman', 'ponytail', 'rdxmin'];
const TASKS = [
  { id: 'cache', kind: 'code', prompt: 'Add a cache layer for our user profile API responses. Show the code.' },
  { id: 'debounce', kind: 'code', prompt: 'Add debounce to a search input that currently fires an API call on every keystroke. Show the code.' },
  { id: 'auth-bug', kind: 'code', prompt: 'Our auth middleware rejects valid tokens at the exact expiry boundary (it uses currentTime > expiry). Find and fix the root cause.' },
  { id: 'pooling', kind: 'prose', prompt: 'Explain how database connection pooling works and why it helps.' },
  { id: 'rest-graphql', kind: 'prose', prompt: 'Summarize the main tradeoffs between REST and GraphQL for a new API.' },
  { id: 'regex-concept', kind: 'prose', prompt: 'Explain what a regular expression backreference is, with one short example.' },
];

// Long answers are truncated for the page, but the token count always reflects
// the FULL billed response — truncating the text and then quoting a shrunken
// number would misreport the thing being measured.
const MAX_CHARS = 1400;

function cell(task, arm) {
  const p = path.join(RAW, `${task}__${arm}.json`);
  let d;
  try { d = JSON.parse(fs.readFileSync(p, 'utf8')); } catch (_) { return null; }
  if (!d || d.is_error) return null;
  const full = (d.result || '').trim();
  const truncated = full.length > MAX_CHARS;
  return {
    tokens: d.usage.output_tokens,
    lines: full ? full.split('\n').length : 0,
    chars: full.length,
    truncated,
    text: truncated ? full.slice(0, MAX_CHARS) : full,
  };
}

// Aggregates over ALL suites, so the site can offer more than one metric
// without inventing numbers: billed tokens is the bill, answer lines is what
// the reader actually wades through.
const ALL_RAW = ['raw', 'raw-sonnet', 'raw-verify'].map((d) =>
  path.join(ROOT, 'benchmarks', 'results', d));
const KINDS = require('../benchmarks/aggregate').KIND;

function aggregates() {
  const cells = {};
  for (const dir of ALL_RAW) {
    let files = [];
    try { files = fs.readdirSync(dir); } catch (_) { continue; }
    for (const f of files) {
      const m = f.match(/^(.+)__([a-z]+)\.json$/);
      if (!m) continue;
      let d;
      try { d = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')); } catch (_) { continue; }
      if (!d || d.is_error) continue;
      const text = (d.result || '').trim();
      (cells[`${dir}|${m[1]}`] ||= {})[m[2]] = {
        tokens: d.usage.output_tokens,
        lines: text ? text.split('\n').length : 0,
      };
    }
  }
  const rows = [];
  for (const k of Object.keys(cells)) {
    const c = cells[k];
    if (!c.vanilla || !ARMS.every((a) => c[a])) continue;
    rows.push({ task: k.split('|')[1], kind: KINDS[k.split('|')[1]] || 'other', cells: c });
  }
  rows.sort((a, b) => a.cells.vanilla.tokens - b.cells.vanilla.tokens);
  const median = rows[Math.floor(rows.length / 2)].cells.vanilla.tokens;

  const group = (label, pick) => {
    const g = rows.filter(pick);
    const out = { label, n: g.length };
    for (const metric of ['tokens', 'lines']) {
      const base = g.reduce((s, r) => s + r.cells.vanilla[metric], 0);
      out[metric] = {};
      for (const a of ARMS) {
        if (a === 'vanilla') continue;
        const v = g.reduce((s, r) => s + r.cells[a][metric], 0);
        out[metric][a] = base ? Math.round((v / base) * 100) : 0;
      }
    }
    return out;
  };

  return {
    median,
    groups: [
      group('all tasks', () => true),
      group('coding', (r) => r.kind === 'coding'),
      group('explanation', (r) => r.kind === 'noncoding'),
      group('short answers', (r) => r.cells.vanilla.tokens < median),
      group('long answers', (r) => r.cells.vanilla.tokens >= median),
    ],
  };
}

function build() {
  const tasks = [];
  for (const t of TASKS) {
    const arms = {};
    for (const a of ARMS) {
      const c = cell(t.id, a);
      if (c) arms[a] = c;
    }
    if (arms.vanilla && arms.rdxmin) tasks.push({ ...t, arms });
  }
  return JSON.stringify({
    note: 'Generated by scripts/build-samples.js from benchmarks/results/raw/. Do not edit by hand.',
    suite: 'June 4-arm suite, Haiku, isolated configs; arms differ only in the injected system prompt.',
    tasks,
    aggregates: aggregates(),
  }, null, 2) + '\n';
}

function main() {
  const json = build();
  if (process.argv.includes('--check')) {
    let have = '';
    try { have = fs.readFileSync(OUT, 'utf8'); } catch (_) {}
    if (have !== json) {
      console.error('site/src/data/samples.json is stale. Run: node scripts/build-samples.js');
      process.exit(1);
    }
    console.log('samples.json in sync.');
    return;
  }
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, json);
  const n = JSON.parse(json).tasks.length;
  console.log(`wrote ${path.relative(ROOT, OUT)} — ${n} tasks`);
}

main();
